### ISSUE TITLE
Does this support restoration of backed up data?

### ISSUE THREAD

**Issue by distbit0** [darchap/android-backup-tool#1]
Hey this looks very interesting but it is not clear if I can use the backups it produces to later restore to my device. Is this possible? Also out of interest does it backup everything (e.g. including media and app data) or only some data, such as apks?

many thx

**Comment by darchap** [comment]
Hello, I'm really sorry for my late reply. Yes, you can use this to restore your data as well. I've just updated the README file, so instructions are more clear. 

Regarding your other question, I use Swift Backup for that task, and then with my script I back up my internal storage (including swift backup folder) 

Feel free to ask anything you want. Regards.
